on:
  push:
    branches:
      - '**'

jobs:
  docker-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build frontend docker image
        uses: docker/build-push-action@v4
        with:
          context: '{{defaultContext}}:frontend'
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v7
          push: true
          tags: |
            xddxdd/bird-lg-go:develop
            xddxdd/bird-lg-go:develop-${{ github.sha }}

      - name: Build proxy docker image
        uses: docker/build-push-action@v4
        with:
          context: '{{defaultContext}}:proxy'
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v7
          push: true
          tags: |
            xddxdd/bird-lgproxy-go:develop
            xddxdd/bird-lgproxy-go:develop-${{ github.sha }}
