on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'master'

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4

      - run: |
          export GO111MODULE=on
          cd frontend
          go get -v -t -d ./...
          go test -v ./...
          cd ..

      - run: |
          export GO111MODULE=on
          cd proxy
          go get -v -t -d ./...
          go test -v ./...
          cd ..
